name: Build and deploy to GitHub Pages

on:
    push:
        branches: main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2.3.1
            # Setup key
            - run: set -eu
            - run: mkdir "$HOME/.ssh"
            - run: echo "${{ secrets.server-key }}" > "$HOME/.ssh/server-key"
            - run: chmod 600 "$HOME/.ssh/server-key"
            # Build - используем если есть файл установзик package.json
            # - name: Install, lint, build 🔧
            #   run: |
            #       npm install 
            #       npm run build
            # END Build

            # Deploy
            - name: Deploy 🚀
            - run: cd app && rsync -e "ssh -p 20022 -i "$HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . denysmyr@denys-myr.com:21098/home/denysmyr/public_html
